#!/usr/bin/env bash

# This software was created by the Wellcome Centre for Anti-Infectives Research using Wellcome Trust funding
# batch_brb  Copyright (C) 2020  University of Dundee
# For full details see LICENSE.txt or http://www.gnu.org/licenses/

####This script will setup the batch_brb work area
#Usage: batch_brb_setup

set -euo pipefail

#Create directories
mkdir -p batch_brb/{databases,jobs,templates/{CSVs,Excel_files},documentation}
cd batch_brb

#Copy data into folders
cp ${CONDA_PREFIX}/etc/01_batch_makeblastdb_template.csv templates/CSVs/
cp ${CONDA_PREFIX}/etc/02_make_aliasdb_template.csv templates/CSVs/
cp ${CONDA_PREFIX}/etc/03_accession_retrieve_template.csv templates/CSVs/
cp ${CONDA_PREFIX}/etc/04_orthology_pipeline_form_template.csv templates/CSVs/
cp ${CONDA_PREFIX}/etc/delete_database_template.csv templates/CSVs/
cp ${CONDA_PREFIX}/etc/01_batch_makeblastdb_template.xlsx templates/Excel_files/
cp ${CONDA_PREFIX}/etc/02_make_aliasdb_template.xlsx templates/Excel_files/
cp ${CONDA_PREFIX}/etc/03_accession_retrieve_template.xlsx templates/Excel_files/
cp ${CONDA_PREFIX}/etc/04_orthology_pipeline_form_template.xlsx templates/Excel_files/
cp ${CONDA_PREFIX}/etc/delete_database_template.xlsx templates/Excel_files/

cp ${CONDA_PREFIX}/etc/LICENSE documentation/
cp ${CONDA_PREFIX}/etc/info.txt documentation/
cp ${CONDA_PREFIX}/etc/batch_brb_manual.pdf documentation/


#Show welcome message
cat ${CONDA_PREFIX}/etc/info.txt

echo
echo
echo "batch_brb located $(pwd)"
echo
echo