#!/usr/bin/env bash

# This software was created by the Wellcome Centre for Anti-Infectives Research using Wellcome Trust funding
# batch_brb  Copyright (C) 2020  University of Dundee
# For full details see LICENSE.txt or http://www.gnu.org/licenses/

#### This script will show the batch_brb licence
#Usage: show


cat ${CONDA_PREFIX}/etc/documentation/LICENSE
